[package]
name = "autograder"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
clap = "3.0.0-beta.4"
anyhow = "1.0"
colored = "2.0"